from enum import Enum

class SentimentCategory(Enum):
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"

class ComponentType(Enum):
    BAR_CHART = "bar_chart"
    LINE_CHART = "line_chart"
    PIE_CHART = "pie_chart"
    WORD_CLOUD = "word_cloud"
    SENTIMENT_ANALYSIS = "sentiment_analysis"
    TREND_ANALYSIS = "trend_analysis"
    
class AgeRange(str, Enum):
    age_18_24 = "18-24"
    age_25_34 = "25-34"
    age_35_44 = "35-44"
    age_45_54 = "45-54"
    age_55_64 = "55-64"
    age_65_plus = "65+"
    other = "other"

class Gender(str, Enum):
    female = "female"
    male = "male"
    other = "other"
    prefer_not_to_say = "prefer not to say"

class EducationLevel(str, Enum):
    elementary = "elementary"
    highschool = "highschool"
    bachelor = "bachelor"
    master = "master"
    phd = "phd"
    other = "other"

class Country(str, Enum):
    brazil = "Brazil"
    argentina = "Argentina"
    chile = "Chile"
    colombia = "Colombia"
    peru = "Peru"
    mexico = "Mexico"
    united_states = "United States"
    canada = "Canada"
    portugal = "Portugal"
    spain = "Spain"
    germany = "Germany"
    france = "France"
    italy = "Italy"
    united_kingdom = "United Kingdom"
    netherlands = "Netherlands"
    switzerland = "Switzerland"
    australia = "Australia"
    japan = "Japan"
    south_korea = "South Korea"
    china = "China"
    india = "India"
    south_africa = "South Africa"
    angola = "Angola"
    mozambique = "Mozambique"
    other = "Other"

class State(str, Enum):
    AC = "AC"
    AL = "AL"
    AP = "AP"
    AM = "AM"
    BA = "BA"
    CE = "CE"
    DF = "DF"
    ES = "ES"
    GO = "GO"
    MA = "MA"
    MT = "MT"
    MS = "MS"
    MG = "MG"
    PA = "PA"
    PB = "PB"
    PR = "PR"
    PE = "PE"
    PI = "PI"
    RJ = "RJ"
    RN = "RN"
    RS = "RS"
    RO = "RO"
    RR = "RR"
    SC = "SC"
    SP = "SP"
    SE = "SE"
    TO = "TO"
    other = "Other"